**What is Pytorch about?**

The fundamental data structure in Pytorch is "tensor". In the context ofdeep learning, tensors refer to the generalization of vectors and matrices to an arbitrary number of dimensions. Another name for the same concept is multidimensional array.

"The dimensionality of a tensor coincides with the number of indexes used to refer to "scalar values" within the tensor."

"Compared to NumPy arrays, PyTorch tensors have a few superpowers, such as the ability to perform very fast operations on graphical processing units (GPUs)distribute operations on multiple devices or machines."

**(Reference:Stevens, E., Antiga, L., & Viehmann, T. (2020). Deep learning with PyTorch. Manning Publications.)**

In [ ]:
import torch

In [ ]:
torch.__version__

'2.1.0+cu121'

## *What is tensor?*

Please watch this Youtube video to understand the basics about tensors. https://www.youtube.com/watch?v=Csa5R12jYRg&t=291s


**CREATION OF TENSORS**

A scalar is a single number.It has zero dimension.

A vector has more than one number but it has one dimenion.

A matrix has two dimensions.Remember that number of dimensionality is the number of indexes requires to index a single value from a tensor.



In [ ]:
scalar = torch.tensor(55)
print(scalar)
print(scalar.ndim)

tensor(55)
0


In [ ]:
## How to retrieve Python's integer from the tensor having a single value? We need item method.
scalar.item() ## Returns you Python integer

55

In [ ]:
vector = torch.tensor([5,6,7,8]) ##We pass a Python's list with multiple elements to create a vector.All elements of that list must of numeric data type.
print(vector)
print(vector.ndim)

tensor([5, 6, 7, 8])
1


In [ ]:

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])  ## a list of multiple nested (Python's) list is required to create a Matrix
print(MATRIX)
print(MATRIX.ndim)

tensor([[ 7,  8],
        [ 9, 10]])
2


In [ ]:
## Tensors are high-dimensional data structure. It can represent images, videoes and text data.
TENSOR = torch.tensor([[[7, 0, 3, 6],
                        [3, 6, 9, 8],
                        [2, 5, 5, 15]]]) ## three Python's list wrapped in a list which is wrapped in another Python'list
print(TENSOR)
print(TENSOR.ndim)

tensor([[[ 7,  0,  3,  6],
         [ 3,  6,  9,  8],
         [ 2,  5,  5, 15]]])
3


**Shape attribute** gives the maximum number of elements in each dimension of a tensor.Therefore, it also gives the total number of elements in a tensor.

In [ ]:
print(scalar.shape)
print(vector.shape)
print(MATRIX.shape)
print(TENSOR.shape)

torch.Size([])
torch.Size([4])
torch.Size([2, 2])
torch.Size([1, 3, 4])


**RANDOM TENSORS**
We try to learn weights in ML/DL mdoels. These weights are randomly initialized.These weights are updated through the process of optimization. Therefore, the tensors with random weights are very interesting to understand.

In [ ]:
random_tensors = torch.rand(size = (3,3), dtype = torch.float)
print(random_tensors)

tensor([[9.0564e-01, 4.1595e-01, 5.4787e-01],
        [9.1831e-01, 5.2986e-01, 6.4479e-01],
        [5.5712e-04, 6.2986e-01, 5.5266e-01]])


**TENSORS WITH ALL ONES AND ZEROS**

In [ ]:
zero_tensor = torch.zeros(size = (5,5))
print(zero_tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
ones_tensor = torch.ones(size = (4,3))
print(ones_tensor)
print(ones_tensor.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


**Creating a sequence of data with arange method of torch**

In [ ]:
sequence_of_number = torch.arange(start = 0, end = 10, step = 1)
print(sequence_of_number)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
sequence_of_number.view(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

At the time of creating tensors we can specify

*   Datatype of elements of a tensor
*   Device on which to store the tensor. We cannot take the dot product of tensors stored on two different devices, one on cpu and the other on gpu.
*   Whether we want to record the history of mathematical operations on tensors for the purpose of computing gradients.




In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

**TENSOR OPERATIONS (ELEMENTWISE OPERATIONS**

We don't need to write for loop to perform the same operation on all the elements of a tensor.

*   Addition
*   Subtraction
*   Multiplication
*   Division
*   Matrix multiplication



In [ ]:
simple_tensor = torch.tensor([8, 9, 14, 17])

In [ ]:
#Addition
simple_tensor + 10

tensor([18, 19, 24, 27])

In [ ]:
#Multiplication
simple_tensor * 11

tensor([ 88,  99, 154, 187])

In [ ]:
#Division
simple_tensor/5

tensor([1.6000, 1.8000, 2.8000, 3.4000])

In [ ]:
## Elementwise multiplication of elements in two vectors having same size
vector_basic1 = torch.tensor([5, 6, 7, 8, 9])
vector_basic2 = torch.tensor([1, 2, 3, 4, 5])
vector_basic1*vector_basic2


tensor([ 5, 12, 21, 32, 45])

**MATRIX MULTIPLICATION**

Shape errors are the most common in tensor operations. For matrix multiplication, number of columns in the first matrix must be equal to number of rows in the second matrix. The resulting matrix will be equal to number of rows in the first matrix and the number of columns in the second matrix.

In [ ]:
random_tensor1 = torch.rand(2,4)
print(random_tensor1)

tensor([[0.1053, 0.6358, 0.8100, 0.5604],
        [0.9108, 0.9914, 0.4210, 0.0538]])


In [ ]:
random_tensor2 = torch.rand(4,2)
print(random_tensor2)

tensor([[0.9121, 0.4168],
        [0.6338, 0.2276],
        [0.8645, 0.4073],
        [0.1131, 0.6130]])


In [ ]:
torch.matmul(random_tensor1, random_tensor2) ##torch.mm is a short name for torch.matmul()

tensor([[1.2627, 0.8620],
        [1.8291, 0.8097]])

**Summary statistics**

Takes a vector but returns a scalar

*   Min
*   Max
*   Variance
*   Standard deviation
*   sum
*   median



In [ ]:
vector_Stats = torch.arange(100, 700,2)
print(vector_Stats.min())
print(vector_Stats.max())
print(vector_Stats.to(dtype = torch.float).mean()) ## you cannot take mean until the input data type is also float
print(vector_Stats.sum())
print(vector_Stats.to(dtype = torch.float).median())

tensor(100)
tensor(698)
tensor(399.)
tensor(119700)
tensor(398.)


In [ ]:
torch.max(vector_Stats), torch.min(vector_Stats), torch.mean(vector_Stats.to(dtype = torch.float)), torch.sum(vector_Stats) ## Another way to take aggregation of tensors

(tensor(698), tensor(100), tensor(399.), tensor(119700))

In [ ]:
Matrix_stats = torch.rand(5,6)
print(Matrix_stats)
Matrix_stats.sum(dim = 1)

tensor([[0.2771, 0.8647, 0.7157, 0.2788, 0.0015, 0.5376],
        [0.8107, 0.5450, 0.1043, 0.7332, 0.6019, 0.8027],
        [0.6497, 0.0356, 0.5246, 0.0546, 0.6727, 0.7441],
        [0.5155, 0.9807, 0.5743, 0.7775, 0.0662, 0.8659],
        [0.3098, 0.6865, 0.8202, 0.0953, 0.1963, 0.3169]])


tensor([2.6754, 3.5979, 2.6814, 3.7801, 2.4248])

**Change Tensor datatype after it is created**

We can specify the datatype of tensor at the time of creating the tensor. However, we can change the datatype of tensor even after the creation.

torch.Tensor.type(dtype=None)

tensor_name.to(dtype = None)


In [ ]:
seq_tensor = torch.arange(1,10,1, dtype= torch.float64)

In [ ]:
seq_tensor.dtype ## All the elements of the tensor are of float64 type.

torch.float64

In [ ]:
seq_tensor_int = seq_tensor.type(dtype = torch.int32)

In [ ]:
seq_tensor_int

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

## **SQUEEZING and UNSQUEEZING**

**Squeezing of a tensor:** If any dimension of a tensor has value equal to 1, squeezing removes that dimension.

(1,2,3)-------->>>>(2,3)

(2,3,1)-------->>>>(2,3)


**Unsqueezing of a tensor:** This can add the value 1 to the specified dimension.

(2,3)---------->>>>>(1,2,3)

(2,2,3)-------->>>>>(2,1,2,3)

### **SQUEEZING OF A TENSOR**

In [ ]:
zee = torch.tensor([[[1,2,3],[4,5,6]]])

In [ ]:
zee.shape, zee.size()

(torch.Size([1, 2, 3]), torch.Size([1, 2, 3]))

In [ ]:
zee_dim_reduced = torch.squeeze(zee)

In [ ]:
zee_dim_reduced.size()

torch.Size([2, 3])

In [ ]:
another_tensor = zee.reshape((2,3,1))

In [ ]:
another_tensor

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [ ]:
tensor_squeezed = torch.squeeze(another_tensor)

### **UNSQUEEZING OF A TENSOR**

In [ ]:
two_d_tensor = torch.arange(1,7,1).reshape((2,3))

In [ ]:
two_d_tensor.shape

torch.Size([2, 3])

In [ ]:
torch.unsqueeze(two_d_tensor, 0 ) ## Added one in the first dimension

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [ ]:
three_d_tensor = torch.arange(0,12,1).reshape((2,2,3))

In [ ]:
three_d_tensor_unsqueezed = torch.unsqueeze(three_d_tensor, 2 )

In [ ]:
three_d_tensor.shape, three_d_tensor_unsqueezed.shape

(torch.Size([2, 2, 3]), torch.Size([2, 2, 1, 3]))

In [ ]:
three_d_tensor.ndim, three_d_tensor_unsqueezed.ndim

(3, 4)

## **Reshaping tensors**

Two methods for reshaping the tensors: **reshape() versus view()**

What is the difference between the two methods?

The difference is actually quite confusing.

view() always returns the view of the original tensor, meaning that the returned tensor shares the same memory with the original tensor.

reshape() returns the view or copy of the original tensor. The reshape() method may or may not return the memory with the original tensor.Pytorch documentation says "When possible, the returned tensor will be a view of input. Otherwise, it will be a copy."

## **Reshape**

In [ ]:
aa = torch.arange(0,12,1)

In [ ]:
aa_reshaped = aa.reshape((2,3,2))

In [ ]:
aa_reshaped[0,0,1] = 55

In [ ]:
aa_reshaped, aa ## In this case the reshaped tensor "aa_reshaped" is the view of original tensor "aa"

(tensor([[[ 0, 55],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]]]),
 tensor([ 0, 55,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [ ]:
## Use clone() method to surely get the copy of the original tensor.

In [ ]:
aa = torch.arange(0,12,1)

In [ ]:
aa_reshaped = aa.reshape((2,3,2)).clone() ## using clone method to obtain the copy. Tensor "aa_reshaped" is the copy of the tensor "aa".

In [ ]:
aa_reshaped[0,0,1] = 55

In [ ]:
aa_reshaped, aa

(tensor([[[ 0, 55],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]]]),
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

## **View**

In [ ]:
even_num = torch.arange(0,19, 2)

In [ ]:
even_num_reshaped = even_num.view((5,2))

In [ ]:
even_num, even_num_reshaped

(tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),
 tensor([[ 0,  2],
         [ 4,  6],
         [ 8, 10],
         [12, 14],
         [16, 18]]))

In [ ]:
even_num_reshaped[2,1] = -999 ## since "even_num_reshaped" is a view, the changes in "even_num_reshaped" will be reflected in the original tensor "even_num"

In [ ]:
even_num, even_num_reshaped

(tensor([   0,    2,    4,    6,    8, -999,   12,   14,   16,   18]),
 tensor([[   0,    2],
         [   4,    6],
         [   8, -999],
         [  12,   14],
         [  16,   18]]))

## **INDEXING AND SLICING OF TENSORS**

## *One_dimensional tensor*

In [ ]:
oneD_tensor = torch.arange(0,10, 1)
oneD_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## Indexing
oneD_tensor[0]


tensor(0)

In [ ]:
## slicing
oneD_tensor[2:6:2]

tensor([2, 4])

In [ ]:
## Fancy indexing and slicing with tensors
oneD_tensor[torch.tensor([0, 7, 9])]

tensor([0, 7, 9])

## *Two dimensional Tensor*

In [ ]:
two_d_tensor = torch.arange(0, 9 ,1).reshape(3,3)
two_d_tensor

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
## Indexing
two_d_tensor[1, 1] ## we can use item() method to retrieve an integer from the tensor

tensor(4)

In [ ]:
## Slicing
two_d_tensor[0,:]

tensor([0, 1, 2])

In [ ]:
two_d_tensor[0][2]

tensor(2)

In [ ]:
##Fancy slicing
ss = torch.arange(0,16).reshape(4,4).type(dtype = torch.float32)
ss

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [ ]:
ss[:, [0,2,3]]

tensor([[ 0.,  2.,  3.],
        [ 4.,  6.,  7.],
        [ 8., 10., 11.],
        [12., 14., 15.]])

## **Modification/Replacement of values in tensors**

We replace the single value or group of values in a tensor in the same way as it happens in Numpy arrays.

In [ ]:
ss

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [ ]:
ss[2,2] = -999

In [ ]:
ss

tensor([[   0.,    1.,    2.,    3.],
        [   4.,    5.,    6.,    7.],
        [   8.,    9., -999.,   11.],
        [  12.,   13.,   14.,   15.]])

In [ ]:
ss[:, 3] = torch.tensor([-5,-6,-7,-8])

In [ ]:
ss

tensor([[   0.,    1.,    2.,   -5.],
        [   4.,    5.,    6.,   -6.],
        [   8.,    9., -999.,   -7.],
        [  12.,   13.,   14.,   -8.]])

## **INTEROPERABILITY OF NUMPY AND PYTORCH**

Yes, we can convert numpy arrays into tensors and vice versa. Numpy arrays provide the foundation for many machine learning and deep learning libraries.

We can convert numpy arrays into pytorch tensors using **torch.from_numpy(ndarray)** method.

Similarly we can convert tensors into numpy arrays into tensors using **torch.Tensor.numpy()**

In [ ]:
import numpy as np

In [ ]:
two_d_array = np.array([[1, 2, 3],[4, 5, 6]])
two_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
two_d_tensor = torch.tensor([[-9, -8, 3],[7, 15, 16]])
two_d_tensor

tensor([[-9, -8,  3],
        [ 7, 15, 16]])

In [ ]:
#two_d_array + two_d_tensor   ## will give an error if we try to add one numpy array and the other tensor

In [ ]:
two_d_array_to_tensor = torch.from_numpy(two_d_array)
two_d_array_to_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
## Then we can add two tensors
two_d_tensor + two_d_array_to_tensor

tensor([[-8, -6,  6],
        [11, 20, 22]])

In [ ]:
two_d_tensor_to_array = torch.Tensor.numpy(two_d_tensor)
two_d_tensor_to_array

array([[-9, -8,  3],
       [ 7, 15, 16]])

In [ ]:
two_d_array + two_d_tensor_to_array

array([[-8, -6,  6],
       [11, 20, 22]])

In [ ]:
torch.cuda.is_available()

True